- name: Add Debian preferences for Chromium
  tags:
    - chromium
    - apt
    - no-snap
  ansible.builtin.copy:
    mode: "0600"
    dest: "/etc/apt/preferences.d/chromium-debian.pref"
    content: |
      Package: *
      Pin: origin "deb.debian.org"
      Pin-Priority: -10
      Package: chromium* libvpx5 libjpeg62-turbo
      Pin: origin "deb.debian.org"
      Pin-Priority: 999

- name: Add Debian stable repo
  tags:
    - chromium
    - apt
    - no-snap
  ansible.builtin.copy:
    mode: "0600"
    dest: "/etc/apt/sources.list.d/debian-stable.list"
    content: |
      deb http://deb.debian.org/debian stable main

- name: Import Debian apt key
  tags:
    - chromium
    - apt
    - no-snap
  ansible.builtin.command:
    cmd: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9

# N.B. Chromium profile dir is in ~/.config/chromium
