- name: Add Debian preferences for Chromium
  tags:
    - chromium
    - apt
    - no-snap
  become: true
  ansible.builtin.copy:
    mode: "0644"
    dest: "/etc/apt/preferences.d/chromium-debian.pref"
    content: |
      Package: *
      Pin: origin "deb.debian.org"
      Pin-Priority: -10
      Package: chromium* libvpx5 libjpeg62-turbo
      Pin: origin "deb.debian.org"
      Pin-Priority: 999

- name: Add Debian stable repo
  tags:
    - chromium
    - apt
    - no-snap
  become: true
  ansible.builtin.copy:
    mode: "0644"
    dest: "/etc/apt/sources.list.d/debian-stable.list"
    content: |
      deb http://deb.debian.org/debian stable main

- name: Add an apt key by id from a keyserver
  become: true
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0E98404D386FA1D9
  tags:
    - chromium
    - apt
    - no-snap


# N.B. Chromium profile dir is in ~/.config/chromium
