- name: Install ZSH
  ansible.builtin.apt:
    name: zsh
  tags: 'zsh'

# - name: Change shell to zsh
#   shell: chsh -s $(which zsh) kakadu
#   tags: 'zsh'
#   become_user: kakadu

- name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
  ansible.builtin.user:
    name: kakadu
    shell: /usr/bin/zsh

- name: Check that the Oh-my-zsh already installed
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
  register: oh_my_stats
  tags: 'zsh'

- name: Download Oh-My-Zsh
  ansible.builtin.get_url:
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: ~/.oh-my-installer
    mode: '0500'
  when: not oh_my_stats.stat.exists

- name: Install Oh-My-Zsh
  ansible.builtin.command: ~/.oh-my-installer
  tags: 'zsh'
  when: not oh_my_stats.stat.exists

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
    refspec: 'v0.7.0'
  tags: 'zsh'
